name: Deploy react app

on: 
    pull_request:
      branches:
        - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.VPS_HOST }}
        USERNAME: ${{ secrets.VPS_USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "~/projetLol/app/"
    
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
          HOST: ${{ secrets.VPS_HOST }}
          USERNAME: ${{ secrets.VPS_USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: cd ~/projetLol/app/ && yarn build && sudo rm -r /var/www/html/ && sudo mkdir /var/www/html/ && sudo mv ./build/* /var/www/html/ 
